export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST" ;
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS" ;
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE" ;

export const GET_MYPOSTS_REQUEST = "GET_POSTS_REQUEST" ;
export const GET_MYPOSTS_SUCCESS = "GET_POSTS_SUCCESS" ;
export const GET_MYPOSTS_FAILURE = "GET_POSTS_FAILURE" ;

export const GET_DRAFTS_REQUEST = "GET_DRAFTS_REQUEST" ;
export const GET_DRAFTS_SUCCESS = "GET_DRAFTS_SUCCESS" ;
export const GET_DRAFTS_FAILURE = "GET_DRAFTS_FAILURE" ;

export const GET_POST_REQUEST = "GET_POST_REQUEST" ;
export const GET_POST_SUCCESS = "GET_POST_SUCCESS" ;
export const GET_POST_FAILURE = "GET_POST_FAILURE" ;

export const CREATE_POST = "CREATE_POST" ;